# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
