# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(db_index=True, max_length=11)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_joined', models.DateTimeField(default=datetime.datetime(2016, 12, 26, 1, 24, 24, 534387, tzinfo=utc))),
                ('birthday', models.DateField(blank=True)),
            ],
        ),
    ]
